redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Sandiwa Project\\Sandiwa2\\.netlify\\v1\\functions"
functionsDirectoryOrigin = "config"
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Sandiwa Project\\Sandiwa2\\dist\\client"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Sandiwa Project\\Sandiwa2\\.netlify\\v1\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*.jpg"
to = "/:splat.jpg"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.png"
to = "/:splat.png"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*.ico"
to = "/:splat.ico"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]