/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MentorApplicationSuccessRouteImport } from './routes/mentor-application-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplyMentorRouteImport } from './routes/apply-mentor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorDashboardRouteImport } from './routes/mentor/dashboard'
import { Route as MentorLayoutRouteImport } from './routes/mentor/_layout'
import { Route as LearnerPaymentSuccessRouteImport } from './routes/learner/payment-success'
import { Route as LearnerDashboardRouteImport } from './routes/learner/dashboard'
import { Route as LearnerCheckoutRouteImport } from './routes/learner/checkout'
import { Route as LearnerLayoutRouteImport } from './routes/learner/_layout'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as MentorStudentsIndexRouteImport } from './routes/mentor/students/index'
import { Route as MentorSettingsIndexRouteImport } from './routes/mentor/settings/index'
import { Route as MentorReviewsIndexRouteImport } from './routes/mentor/reviews/index'
import { Route as MentorProfileIndexRouteImport } from './routes/mentor/profile/index'
import { Route as MentorNotificationsIndexRouteImport } from './routes/mentor/notifications/index'
import { Route as MentorEncyclopediaIndexRouteImport } from './routes/mentor/encyclopedia/index'
import { Route as MentorEarningsIndexRouteImport } from './routes/mentor/earnings/index'
import { Route as MentorCoursesIndexRouteImport } from './routes/mentor/courses/index'
import { Route as MentorCommunityIndexRouteImport } from './routes/mentor/community/index'
import { Route as MentorAnalyticsIndexRouteImport } from './routes/mentor/analytics/index'
import { Route as LearnerSettingsIndexRouteImport } from './routes/learner/settings/index'
import { Route as LearnerSavedIndexRouteImport } from './routes/learner/saved/index'
import { Route as LearnerProfileIndexRouteImport } from './routes/learner/profile/index'
import { Route as LearnerNotificationsIndexRouteImport } from './routes/learner/notifications/index'
import { Route as LearnerEncyclopediaIndexRouteImport } from './routes/learner/encyclopedia/index'
import { Route as LearnerCommunityIndexRouteImport } from './routes/learner/community/index'
import { Route as LearnerCertificatesIndexRouteImport } from './routes/learner/certificates/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as MentorStudentsStudentIdRouteImport } from './routes/mentor/students/$studentId'
import { Route as MentorProfileEditRouteImport } from './routes/mentor/profile/edit'
import { Route as MentorEncyclopediaCreateRouteImport } from './routes/mentor/encyclopedia/create'
import { Route as MentorEncyclopediaArticleIdRouteImport } from './routes/mentor/encyclopedia/$articleId'
import { Route as MentorEarningsWithdrawalsRouteImport } from './routes/mentor/earnings/withdrawals'
import { Route as MentorCoursesCreateRouteImport } from './routes/mentor/courses/create'
import { Route as MentorAnalyticsEngagementRouteImport } from './routes/mentor/analytics/engagement'
import { Route as MentorAnalyticsCoursesRouteImport } from './routes/mentor/analytics/courses'
import { Route as MentorAnalyticsCompletionRouteImport } from './routes/mentor/analytics/completion'
import { Route as LearnerProfileEditRouteImport } from './routes/learner/profile/edit'
import { Route as LearnerLearnCourseIdRouteImport } from './routes/learner/learn/$courseId'
import { Route as LearnerEncyclopediaArticleIdRouteImport } from './routes/learner/encyclopedia/$articleId'
import { Route as AdminUsersAuditLogsRouteImport } from './routes/admin/users/audit-logs'
import { Route as AdminPaymentsTransactionsRouteImport } from './routes/admin/payments/transactions'
import { Route as AdminPaymentsReportedContentRouteImport } from './routes/admin/payments/reported-content'
import { Route as AdminPaymentsPayoutsRouteImport } from './routes/admin/payments/payouts'
import { Route as AdminCoursesEditRouteImport } from './routes/admin/courses/edit'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'
import { Route as MentorCommunityEventsIndexRouteImport } from './routes/mentor/community/events/index'
import { Route as MentorCommunityDiscussionsIndexRouteImport } from './routes/mentor/community/discussions/index'
import { Route as LearnerMentorsMentorsIndexRouteImport } from './routes/learner/mentors/mentors.index'
import { Route as LearnerCoursesCoursesIndexRouteImport } from './routes/learner/courses/courses.index'
import { Route as LearnerCommunityEventsIndexRouteImport } from './routes/learner/community/events/index'
import { Route as LearnerCommunityDiscussionsIndexRouteImport } from './routes/learner/community/discussions/index'
import { Route as AdminUsersMentorsIndexRouteImport } from './routes/admin/users/mentors/index'
import { Route as MentorEncyclopediaArticleIdEditRouteImport } from './routes/mentor/encyclopedia/$articleId/edit'
import { Route as MentorCoursesManageCertificatesRouteImport } from './routes/mentor/courses/manage/certificates'
import { Route as MentorCoursesManageCourseIdRouteImport } from './routes/mentor/courses/manage.$courseId'
import { Route as MentorCoursesEditCourseIdRouteImport } from './routes/mentor/courses/edit.$courseId'
import { Route as MentorCommunityEventsCreateRouteImport } from './routes/mentor/community/events/create'
import { Route as MentorCommunityEventsEventIdRouteImport } from './routes/mentor/community/events/$eventId'
import { Route as MentorCommunityDiscussionsNewRouteImport } from './routes/mentor/community/discussions/new'
import { Route as MentorCommunityDiscussionsDiscussionIdRouteImport } from './routes/mentor/community/discussions/$discussionId'
import { Route as LearnerMentorsMentorsMentorIdRouteImport } from './routes/learner/mentors/mentors.$mentorId'
import { Route as LearnerCoursesCoursesCourseIdRouteImport } from './routes/learner/courses/courses.$courseId'
import { Route as LearnerCommunityEventsCreateRouteImport } from './routes/learner/community/events/create'
import { Route as LearnerCommunityEventsEventIdRouteImport } from './routes/learner/community/events/$eventId'
import { Route as LearnerCommunityDiscussionsNewRouteImport } from './routes/learner/community/discussions/new'
import { Route as LearnerCommunityDiscussionsDiscussionIdRouteImport } from './routes/learner/community/discussions/$discussionId'
import { Route as MentorCoursesManageReviewsCourseIdRouteImport } from './routes/mentor/courses/manage/reviews.$courseId'
import { Route as MentorCommunityEventsEventIdEditRouteImport } from './routes/mentor/community/events/$eventId.edit'
import { Route as LearnerCommunityEventsEventIdEditRouteImport } from './routes/learner/community/events/$eventId.edit'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorApplicationSuccessRoute =
  MentorApplicationSuccessRouteImport.update({
    id: '/mentor-application-success',
    path: '/mentor-application-success',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMentorRoute = ApplyMentorRouteImport.update({
  id: '/apply-mentor',
  path: '/apply-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorLayoutRoute = MentorLayoutRouteImport.update({
  id: '/mentor/_layout',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerPaymentSuccessRoute = LearnerPaymentSuccessRouteImport.update({
  id: '/learner/payment-success',
  path: '/learner/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/learner/dashboard',
  path: '/learner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerCheckoutRoute = LearnerCheckoutRouteImport.update({
  id: '/learner/checkout',
  path: '/learner/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLayoutRoute = LearnerLayoutRouteImport.update({
  id: '/learner/_layout',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentsIndexRoute = MentorStudentsIndexRouteImport.update({
  id: '/mentor/students/',
  path: '/mentor/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSettingsIndexRoute = MentorSettingsIndexRouteImport.update({
  id: '/mentor/settings/',
  path: '/mentor/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorReviewsIndexRoute = MentorReviewsIndexRouteImport.update({
  id: '/mentor/reviews/',
  path: '/mentor/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorProfileIndexRoute = MentorProfileIndexRouteImport.update({
  id: '/mentor/profile/',
  path: '/mentor/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorNotificationsIndexRoute =
  MentorNotificationsIndexRouteImport.update({
    id: '/mentor/notifications/',
    path: '/mentor/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorEncyclopediaIndexRoute = MentorEncyclopediaIndexRouteImport.update({
  id: '/mentor/encyclopedia/',
  path: '/mentor/encyclopedia/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorEarningsIndexRoute = MentorEarningsIndexRouteImport.update({
  id: '/mentor/earnings/',
  path: '/mentor/earnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCoursesIndexRoute = MentorCoursesIndexRouteImport.update({
  id: '/mentor/courses/',
  path: '/mentor/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCommunityIndexRoute = MentorCommunityIndexRouteImport.update({
  id: '/mentor/community/',
  path: '/mentor/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsIndexRoute = MentorAnalyticsIndexRouteImport.update({
  id: '/mentor/analytics/',
  path: '/mentor/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSettingsIndexRoute = LearnerSettingsIndexRouteImport.update({
  id: '/learner/settings/',
  path: '/learner/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSavedIndexRoute = LearnerSavedIndexRouteImport.update({
  id: '/learner/saved/',
  path: '/learner/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerProfileIndexRoute = LearnerProfileIndexRouteImport.update({
  id: '/learner/profile/',
  path: '/learner/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerNotificationsIndexRoute =
  LearnerNotificationsIndexRouteImport.update({
    id: '/learner/notifications/',
    path: '/learner/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerEncyclopediaIndexRoute =
  LearnerEncyclopediaIndexRouteImport.update({
    id: '/learner/encyclopedia/',
    path: '/learner/encyclopedia/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityIndexRoute = LearnerCommunityIndexRouteImport.update({
  id: '/learner/community/',
  path: '/learner/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerCertificatesIndexRoute =
  LearnerCertificatesIndexRouteImport.update({
    id: '/learner/certificates/',
    path: '/learner/certificates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin/reports/',
  path: '/admin/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/admin/profile/',
  path: '/admin/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin/payments/',
  path: '/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/admin/analytics/',
  path: '/admin/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorStudentsStudentIdRoute = MentorStudentsStudentIdRouteImport.update({
  id: '/mentor/students/$studentId',
  path: '/mentor/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorProfileEditRoute = MentorProfileEditRouteImport.update({
  id: '/mentor/profile/edit',
  path: '/mentor/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorEncyclopediaCreateRoute =
  MentorEncyclopediaCreateRouteImport.update({
    id: '/mentor/encyclopedia/create',
    path: '/mentor/encyclopedia/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorEncyclopediaArticleIdRoute =
  MentorEncyclopediaArticleIdRouteImport.update({
    id: '/mentor/encyclopedia/$articleId',
    path: '/mentor/encyclopedia/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorEarningsWithdrawalsRoute =
  MentorEarningsWithdrawalsRouteImport.update({
    id: '/mentor/earnings/withdrawals',
    path: '/mentor/earnings/withdrawals',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCoursesCreateRoute = MentorCoursesCreateRouteImport.update({
  id: '/mentor/courses/create',
  path: '/mentor/courses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsEngagementRoute =
  MentorAnalyticsEngagementRouteImport.update({
    id: '/mentor/analytics/engagement',
    path: '/mentor/analytics/engagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorAnalyticsCoursesRoute = MentorAnalyticsCoursesRouteImport.update({
  id: '/mentor/analytics/courses',
  path: '/mentor/analytics/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorAnalyticsCompletionRoute =
  MentorAnalyticsCompletionRouteImport.update({
    id: '/mentor/analytics/completion',
    path: '/mentor/analytics/completion',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerProfileEditRoute = LearnerProfileEditRouteImport.update({
  id: '/learner/profile/edit',
  path: '/learner/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLearnCourseIdRoute = LearnerLearnCourseIdRouteImport.update({
  id: '/learner/learn/$courseId',
  path: '/learner/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerEncyclopediaArticleIdRoute =
  LearnerEncyclopediaArticleIdRouteImport.update({
    id: '/learner/encyclopedia/$articleId',
    path: '/learner/encyclopedia/$articleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersAuditLogsRoute = AdminUsersAuditLogsRouteImport.update({
  id: '/admin/users/audit-logs',
  path: '/admin/users/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsTransactionsRoute =
  AdminPaymentsTransactionsRouteImport.update({
    id: '/admin/payments/transactions',
    path: '/admin/payments/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPaymentsReportedContentRoute =
  AdminPaymentsReportedContentRouteImport.update({
    id: '/admin/payments/reported-content',
    path: '/admin/payments/reported-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPaymentsPayoutsRoute = AdminPaymentsPayoutsRouteImport.update({
  id: '/admin/payments/payouts',
  path: '/admin/payments/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesEditRoute = AdminCoursesEditRouteImport.update({
  id: '/admin/courses/edit',
  path: '/admin/courses/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/admin/courses/$courseId',
  path: '/admin/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCommunityEventsIndexRoute =
  MentorCommunityEventsIndexRouteImport.update({
    id: '/mentor/community/events/',
    path: '/mentor/community/events/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityDiscussionsIndexRoute =
  MentorCommunityDiscussionsIndexRouteImport.update({
    id: '/mentor/community/discussions/',
    path: '/mentor/community/discussions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerMentorsMentorsIndexRoute =
  LearnerMentorsMentorsIndexRouteImport.update({
    id: '/learner/mentors/mentors/',
    path: '/learner/mentors/mentors/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCoursesCoursesIndexRoute =
  LearnerCoursesCoursesIndexRouteImport.update({
    id: '/learner/courses/courses/',
    path: '/learner/courses/courses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityEventsIndexRoute =
  LearnerCommunityEventsIndexRouteImport.update({
    id: '/learner/community/events/',
    path: '/learner/community/events/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityDiscussionsIndexRoute =
  LearnerCommunityDiscussionsIndexRouteImport.update({
    id: '/learner/community/discussions/',
    path: '/learner/community/discussions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersMentorsIndexRoute = AdminUsersMentorsIndexRouteImport.update({
  id: '/admin/users/mentors/',
  path: '/admin/users/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorEncyclopediaArticleIdEditRoute =
  MentorEncyclopediaArticleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MentorEncyclopediaArticleIdRoute,
  } as any)
const MentorCoursesManageCertificatesRoute =
  MentorCoursesManageCertificatesRouteImport.update({
    id: '/mentor/courses/manage/certificates',
    path: '/mentor/courses/manage/certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCoursesManageCourseIdRoute =
  MentorCoursesManageCourseIdRouteImport.update({
    id: '/mentor/courses/manage/$courseId',
    path: '/mentor/courses/manage/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCoursesEditCourseIdRoute =
  MentorCoursesEditCourseIdRouteImport.update({
    id: '/mentor/courses/edit/$courseId',
    path: '/mentor/courses/edit/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityEventsCreateRoute =
  MentorCommunityEventsCreateRouteImport.update({
    id: '/mentor/community/events/create',
    path: '/mentor/community/events/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityEventsEventIdRoute =
  MentorCommunityEventsEventIdRouteImport.update({
    id: '/mentor/community/events/$eventId',
    path: '/mentor/community/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityDiscussionsNewRoute =
  MentorCommunityDiscussionsNewRouteImport.update({
    id: '/mentor/community/discussions/new',
    path: '/mentor/community/discussions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityDiscussionsDiscussionIdRoute =
  MentorCommunityDiscussionsDiscussionIdRouteImport.update({
    id: '/mentor/community/discussions/$discussionId',
    path: '/mentor/community/discussions/$discussionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerMentorsMentorsMentorIdRoute =
  LearnerMentorsMentorsMentorIdRouteImport.update({
    id: '/learner/mentors/mentors/$mentorId',
    path: '/learner/mentors/mentors/$mentorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCoursesCoursesCourseIdRoute =
  LearnerCoursesCoursesCourseIdRouteImport.update({
    id: '/learner/courses/courses/$courseId',
    path: '/learner/courses/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityEventsCreateRoute =
  LearnerCommunityEventsCreateRouteImport.update({
    id: '/learner/community/events/create',
    path: '/learner/community/events/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityEventsEventIdRoute =
  LearnerCommunityEventsEventIdRouteImport.update({
    id: '/learner/community/events/$eventId',
    path: '/learner/community/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityDiscussionsNewRoute =
  LearnerCommunityDiscussionsNewRouteImport.update({
    id: '/learner/community/discussions/new',
    path: '/learner/community/discussions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnerCommunityDiscussionsDiscussionIdRoute =
  LearnerCommunityDiscussionsDiscussionIdRouteImport.update({
    id: '/learner/community/discussions/$discussionId',
    path: '/learner/community/discussions/$discussionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCoursesManageReviewsCourseIdRoute =
  MentorCoursesManageReviewsCourseIdRouteImport.update({
    id: '/mentor/courses/manage/reviews/$courseId',
    path: '/mentor/courses/manage/reviews/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorCommunityEventsEventIdEditRoute =
  MentorCommunityEventsEventIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MentorCommunityEventsEventIdRoute,
  } as any)
const LearnerCommunityEventsEventIdEditRoute =
  LearnerCommunityEventsEventIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LearnerCommunityEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/login': typeof LoginRoute
  '/mentor-application-success': typeof MentorApplicationSuccessRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/learner': typeof LearnerLayoutRoute
  '/learner/checkout': typeof LearnerCheckoutRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/payment-success': typeof LearnerPaymentSuccessRoute
  '/mentor': typeof MentorLayoutRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/edit': typeof AdminCoursesEditRoute
  '/admin/payments/payouts': typeof AdminPaymentsPayoutsRoute
  '/admin/payments/reported-content': typeof AdminPaymentsReportedContentRoute
  '/admin/payments/transactions': typeof AdminPaymentsTransactionsRoute
  '/admin/users/audit-logs': typeof AdminUsersAuditLogsRoute
  '/learner/encyclopedia/$articleId': typeof LearnerEncyclopediaArticleIdRoute
  '/learner/learn/$courseId': typeof LearnerLearnCourseIdRoute
  '/learner/profile/edit': typeof LearnerProfileEditRoute
  '/mentor/analytics/completion': typeof MentorAnalyticsCompletionRoute
  '/mentor/analytics/courses': typeof MentorAnalyticsCoursesRoute
  '/mentor/analytics/engagement': typeof MentorAnalyticsEngagementRoute
  '/mentor/courses/create': typeof MentorCoursesCreateRoute
  '/mentor/earnings/withdrawals': typeof MentorEarningsWithdrawalsRoute
  '/mentor/encyclopedia/$articleId': typeof MentorEncyclopediaArticleIdRouteWithChildren
  '/mentor/encyclopedia/create': typeof MentorEncyclopediaCreateRoute
  '/mentor/profile/edit': typeof MentorProfileEditRoute
  '/mentor/students/$studentId': typeof MentorStudentsStudentIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/learner/certificates/': typeof LearnerCertificatesIndexRoute
  '/learner/community/': typeof LearnerCommunityIndexRoute
  '/learner/encyclopedia/': typeof LearnerEncyclopediaIndexRoute
  '/learner/notifications/': typeof LearnerNotificationsIndexRoute
  '/learner/profile/': typeof LearnerProfileIndexRoute
  '/learner/saved/': typeof LearnerSavedIndexRoute
  '/learner/settings/': typeof LearnerSettingsIndexRoute
  '/mentor/analytics/': typeof MentorAnalyticsIndexRoute
  '/mentor/community/': typeof MentorCommunityIndexRoute
  '/mentor/courses/': typeof MentorCoursesIndexRoute
  '/mentor/earnings/': typeof MentorEarningsIndexRoute
  '/mentor/encyclopedia/': typeof MentorEncyclopediaIndexRoute
  '/mentor/notifications/': typeof MentorNotificationsIndexRoute
  '/mentor/profile/': typeof MentorProfileIndexRoute
  '/mentor/reviews/': typeof MentorReviewsIndexRoute
  '/mentor/settings/': typeof MentorSettingsIndexRoute
  '/mentor/students/': typeof MentorStudentsIndexRoute
  '/learner/community/discussions/$discussionId': typeof LearnerCommunityDiscussionsDiscussionIdRoute
  '/learner/community/discussions/new': typeof LearnerCommunityDiscussionsNewRoute
  '/learner/community/events/$eventId': typeof LearnerCommunityEventsEventIdRouteWithChildren
  '/learner/community/events/create': typeof LearnerCommunityEventsCreateRoute
  '/learner/courses/courses/$courseId': typeof LearnerCoursesCoursesCourseIdRoute
  '/learner/mentors/mentors/$mentorId': typeof LearnerMentorsMentorsMentorIdRoute
  '/mentor/community/discussions/$discussionId': typeof MentorCommunityDiscussionsDiscussionIdRoute
  '/mentor/community/discussions/new': typeof MentorCommunityDiscussionsNewRoute
  '/mentor/community/events/$eventId': typeof MentorCommunityEventsEventIdRouteWithChildren
  '/mentor/community/events/create': typeof MentorCommunityEventsCreateRoute
  '/mentor/courses/edit/$courseId': typeof MentorCoursesEditCourseIdRoute
  '/mentor/courses/manage/$courseId': typeof MentorCoursesManageCourseIdRoute
  '/mentor/courses/manage/certificates': typeof MentorCoursesManageCertificatesRoute
  '/mentor/encyclopedia/$articleId/edit': typeof MentorEncyclopediaArticleIdEditRoute
  '/admin/users/mentors/': typeof AdminUsersMentorsIndexRoute
  '/learner/community/discussions/': typeof LearnerCommunityDiscussionsIndexRoute
  '/learner/community/events/': typeof LearnerCommunityEventsIndexRoute
  '/learner/courses/courses/': typeof LearnerCoursesCoursesIndexRoute
  '/learner/mentors/mentors/': typeof LearnerMentorsMentorsIndexRoute
  '/mentor/community/discussions/': typeof MentorCommunityDiscussionsIndexRoute
  '/mentor/community/events/': typeof MentorCommunityEventsIndexRoute
  '/learner/community/events/$eventId/edit': typeof LearnerCommunityEventsEventIdEditRoute
  '/mentor/community/events/$eventId/edit': typeof MentorCommunityEventsEventIdEditRoute
  '/mentor/courses/manage/reviews/$courseId': typeof MentorCoursesManageReviewsCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/login': typeof LoginRoute
  '/mentor-application-success': typeof MentorApplicationSuccessRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/learner': typeof LearnerLayoutRoute
  '/learner/checkout': typeof LearnerCheckoutRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/payment-success': typeof LearnerPaymentSuccessRoute
  '/mentor': typeof MentorLayoutRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/edit': typeof AdminCoursesEditRoute
  '/admin/payments/payouts': typeof AdminPaymentsPayoutsRoute
  '/admin/payments/reported-content': typeof AdminPaymentsReportedContentRoute
  '/admin/payments/transactions': typeof AdminPaymentsTransactionsRoute
  '/admin/users/audit-logs': typeof AdminUsersAuditLogsRoute
  '/learner/encyclopedia/$articleId': typeof LearnerEncyclopediaArticleIdRoute
  '/learner/learn/$courseId': typeof LearnerLearnCourseIdRoute
  '/learner/profile/edit': typeof LearnerProfileEditRoute
  '/mentor/analytics/completion': typeof MentorAnalyticsCompletionRoute
  '/mentor/analytics/courses': typeof MentorAnalyticsCoursesRoute
  '/mentor/analytics/engagement': typeof MentorAnalyticsEngagementRoute
  '/mentor/courses/create': typeof MentorCoursesCreateRoute
  '/mentor/earnings/withdrawals': typeof MentorEarningsWithdrawalsRoute
  '/mentor/encyclopedia/$articleId': typeof MentorEncyclopediaArticleIdRouteWithChildren
  '/mentor/encyclopedia/create': typeof MentorEncyclopediaCreateRoute
  '/mentor/profile/edit': typeof MentorProfileEditRoute
  '/mentor/students/$studentId': typeof MentorStudentsStudentIdRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/learner/certificates': typeof LearnerCertificatesIndexRoute
  '/learner/community': typeof LearnerCommunityIndexRoute
  '/learner/encyclopedia': typeof LearnerEncyclopediaIndexRoute
  '/learner/notifications': typeof LearnerNotificationsIndexRoute
  '/learner/profile': typeof LearnerProfileIndexRoute
  '/learner/saved': typeof LearnerSavedIndexRoute
  '/learner/settings': typeof LearnerSettingsIndexRoute
  '/mentor/analytics': typeof MentorAnalyticsIndexRoute
  '/mentor/community': typeof MentorCommunityIndexRoute
  '/mentor/courses': typeof MentorCoursesIndexRoute
  '/mentor/earnings': typeof MentorEarningsIndexRoute
  '/mentor/encyclopedia': typeof MentorEncyclopediaIndexRoute
  '/mentor/notifications': typeof MentorNotificationsIndexRoute
  '/mentor/profile': typeof MentorProfileIndexRoute
  '/mentor/reviews': typeof MentorReviewsIndexRoute
  '/mentor/settings': typeof MentorSettingsIndexRoute
  '/mentor/students': typeof MentorStudentsIndexRoute
  '/learner/community/discussions/$discussionId': typeof LearnerCommunityDiscussionsDiscussionIdRoute
  '/learner/community/discussions/new': typeof LearnerCommunityDiscussionsNewRoute
  '/learner/community/events/$eventId': typeof LearnerCommunityEventsEventIdRouteWithChildren
  '/learner/community/events/create': typeof LearnerCommunityEventsCreateRoute
  '/learner/courses/courses/$courseId': typeof LearnerCoursesCoursesCourseIdRoute
  '/learner/mentors/mentors/$mentorId': typeof LearnerMentorsMentorsMentorIdRoute
  '/mentor/community/discussions/$discussionId': typeof MentorCommunityDiscussionsDiscussionIdRoute
  '/mentor/community/discussions/new': typeof MentorCommunityDiscussionsNewRoute
  '/mentor/community/events/$eventId': typeof MentorCommunityEventsEventIdRouteWithChildren
  '/mentor/community/events/create': typeof MentorCommunityEventsCreateRoute
  '/mentor/courses/edit/$courseId': typeof MentorCoursesEditCourseIdRoute
  '/mentor/courses/manage/$courseId': typeof MentorCoursesManageCourseIdRoute
  '/mentor/courses/manage/certificates': typeof MentorCoursesManageCertificatesRoute
  '/mentor/encyclopedia/$articleId/edit': typeof MentorEncyclopediaArticleIdEditRoute
  '/admin/users/mentors': typeof AdminUsersMentorsIndexRoute
  '/learner/community/discussions': typeof LearnerCommunityDiscussionsIndexRoute
  '/learner/community/events': typeof LearnerCommunityEventsIndexRoute
  '/learner/courses/courses': typeof LearnerCoursesCoursesIndexRoute
  '/learner/mentors/mentors': typeof LearnerMentorsMentorsIndexRoute
  '/mentor/community/discussions': typeof MentorCommunityDiscussionsIndexRoute
  '/mentor/community/events': typeof MentorCommunityEventsIndexRoute
  '/learner/community/events/$eventId/edit': typeof LearnerCommunityEventsEventIdEditRoute
  '/mentor/community/events/$eventId/edit': typeof MentorCommunityEventsEventIdEditRoute
  '/mentor/courses/manage/reviews/$courseId': typeof MentorCoursesManageReviewsCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-mentor': typeof ApplyMentorRoute
  '/login': typeof LoginRoute
  '/mentor-application-success': typeof MentorApplicationSuccessRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/learner/_layout': typeof LearnerLayoutRoute
  '/learner/checkout': typeof LearnerCheckoutRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/payment-success': typeof LearnerPaymentSuccessRoute
  '/mentor/_layout': typeof MentorLayoutRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/edit': typeof AdminCoursesEditRoute
  '/admin/payments/payouts': typeof AdminPaymentsPayoutsRoute
  '/admin/payments/reported-content': typeof AdminPaymentsReportedContentRoute
  '/admin/payments/transactions': typeof AdminPaymentsTransactionsRoute
  '/admin/users/audit-logs': typeof AdminUsersAuditLogsRoute
  '/learner/encyclopedia/$articleId': typeof LearnerEncyclopediaArticleIdRoute
  '/learner/learn/$courseId': typeof LearnerLearnCourseIdRoute
  '/learner/profile/edit': typeof LearnerProfileEditRoute
  '/mentor/analytics/completion': typeof MentorAnalyticsCompletionRoute
  '/mentor/analytics/courses': typeof MentorAnalyticsCoursesRoute
  '/mentor/analytics/engagement': typeof MentorAnalyticsEngagementRoute
  '/mentor/courses/create': typeof MentorCoursesCreateRoute
  '/mentor/earnings/withdrawals': typeof MentorEarningsWithdrawalsRoute
  '/mentor/encyclopedia/$articleId': typeof MentorEncyclopediaArticleIdRouteWithChildren
  '/mentor/encyclopedia/create': typeof MentorEncyclopediaCreateRoute
  '/mentor/profile/edit': typeof MentorProfileEditRoute
  '/mentor/students/$studentId': typeof MentorStudentsStudentIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/learner/certificates/': typeof LearnerCertificatesIndexRoute
  '/learner/community/': typeof LearnerCommunityIndexRoute
  '/learner/encyclopedia/': typeof LearnerEncyclopediaIndexRoute
  '/learner/notifications/': typeof LearnerNotificationsIndexRoute
  '/learner/profile/': typeof LearnerProfileIndexRoute
  '/learner/saved/': typeof LearnerSavedIndexRoute
  '/learner/settings/': typeof LearnerSettingsIndexRoute
  '/mentor/analytics/': typeof MentorAnalyticsIndexRoute
  '/mentor/community/': typeof MentorCommunityIndexRoute
  '/mentor/courses/': typeof MentorCoursesIndexRoute
  '/mentor/earnings/': typeof MentorEarningsIndexRoute
  '/mentor/encyclopedia/': typeof MentorEncyclopediaIndexRoute
  '/mentor/notifications/': typeof MentorNotificationsIndexRoute
  '/mentor/profile/': typeof MentorProfileIndexRoute
  '/mentor/reviews/': typeof MentorReviewsIndexRoute
  '/mentor/settings/': typeof MentorSettingsIndexRoute
  '/mentor/students/': typeof MentorStudentsIndexRoute
  '/learner/community/discussions/$discussionId': typeof LearnerCommunityDiscussionsDiscussionIdRoute
  '/learner/community/discussions/new': typeof LearnerCommunityDiscussionsNewRoute
  '/learner/community/events/$eventId': typeof LearnerCommunityEventsEventIdRouteWithChildren
  '/learner/community/events/create': typeof LearnerCommunityEventsCreateRoute
  '/learner/courses/courses/$courseId': typeof LearnerCoursesCoursesCourseIdRoute
  '/learner/mentors/mentors/$mentorId': typeof LearnerMentorsMentorsMentorIdRoute
  '/mentor/community/discussions/$discussionId': typeof MentorCommunityDiscussionsDiscussionIdRoute
  '/mentor/community/discussions/new': typeof MentorCommunityDiscussionsNewRoute
  '/mentor/community/events/$eventId': typeof MentorCommunityEventsEventIdRouteWithChildren
  '/mentor/community/events/create': typeof MentorCommunityEventsCreateRoute
  '/mentor/courses/edit/$courseId': typeof MentorCoursesEditCourseIdRoute
  '/mentor/courses/manage/$courseId': typeof MentorCoursesManageCourseIdRoute
  '/mentor/courses/manage/certificates': typeof MentorCoursesManageCertificatesRoute
  '/mentor/encyclopedia/$articleId/edit': typeof MentorEncyclopediaArticleIdEditRoute
  '/admin/users/mentors/': typeof AdminUsersMentorsIndexRoute
  '/learner/community/discussions/': typeof LearnerCommunityDiscussionsIndexRoute
  '/learner/community/events/': typeof LearnerCommunityEventsIndexRoute
  '/learner/courses/courses/': typeof LearnerCoursesCoursesIndexRoute
  '/learner/mentors/mentors/': typeof LearnerMentorsMentorsIndexRoute
  '/mentor/community/discussions/': typeof MentorCommunityDiscussionsIndexRoute
  '/mentor/community/events/': typeof MentorCommunityEventsIndexRoute
  '/learner/community/events/$eventId/edit': typeof LearnerCommunityEventsEventIdEditRoute
  '/mentor/community/events/$eventId/edit': typeof MentorCommunityEventsEventIdEditRoute
  '/mentor/courses/manage/reviews/$courseId': typeof MentorCoursesManageReviewsCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-mentor'
    | '/login'
    | '/mentor-application-success'
    | '/register'
    | '/support'
    | '/admin'
    | '/admin/dashboard'
    | '/learner'
    | '/learner/checkout'
    | '/learner/dashboard'
    | '/learner/payment-success'
    | '/mentor'
    | '/mentor/dashboard'
    | '/admin/courses/$courseId'
    | '/admin/courses/edit'
    | '/admin/payments/payouts'
    | '/admin/payments/reported-content'
    | '/admin/payments/transactions'
    | '/admin/users/audit-logs'
    | '/learner/encyclopedia/$articleId'
    | '/learner/learn/$courseId'
    | '/learner/profile/edit'
    | '/mentor/analytics/completion'
    | '/mentor/analytics/courses'
    | '/mentor/analytics/engagement'
    | '/mentor/courses/create'
    | '/mentor/earnings/withdrawals'
    | '/mentor/encyclopedia/$articleId'
    | '/mentor/encyclopedia/create'
    | '/mentor/profile/edit'
    | '/mentor/students/$studentId'
    | '/admin/analytics/'
    | '/admin/courses/'
    | '/admin/events/'
    | '/admin/payments/'
    | '/admin/profile/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/learner/certificates/'
    | '/learner/community/'
    | '/learner/encyclopedia/'
    | '/learner/notifications/'
    | '/learner/profile/'
    | '/learner/saved/'
    | '/learner/settings/'
    | '/mentor/analytics/'
    | '/mentor/community/'
    | '/mentor/courses/'
    | '/mentor/earnings/'
    | '/mentor/encyclopedia/'
    | '/mentor/notifications/'
    | '/mentor/profile/'
    | '/mentor/reviews/'
    | '/mentor/settings/'
    | '/mentor/students/'
    | '/learner/community/discussions/$discussionId'
    | '/learner/community/discussions/new'
    | '/learner/community/events/$eventId'
    | '/learner/community/events/create'
    | '/learner/courses/courses/$courseId'
    | '/learner/mentors/mentors/$mentorId'
    | '/mentor/community/discussions/$discussionId'
    | '/mentor/community/discussions/new'
    | '/mentor/community/events/$eventId'
    | '/mentor/community/events/create'
    | '/mentor/courses/edit/$courseId'
    | '/mentor/courses/manage/$courseId'
    | '/mentor/courses/manage/certificates'
    | '/mentor/encyclopedia/$articleId/edit'
    | '/admin/users/mentors/'
    | '/learner/community/discussions/'
    | '/learner/community/events/'
    | '/learner/courses/courses/'
    | '/learner/mentors/mentors/'
    | '/mentor/community/discussions/'
    | '/mentor/community/events/'
    | '/learner/community/events/$eventId/edit'
    | '/mentor/community/events/$eventId/edit'
    | '/mentor/courses/manage/reviews/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-mentor'
    | '/login'
    | '/mentor-application-success'
    | '/register'
    | '/support'
    | '/admin'
    | '/admin/dashboard'
    | '/learner'
    | '/learner/checkout'
    | '/learner/dashboard'
    | '/learner/payment-success'
    | '/mentor'
    | '/mentor/dashboard'
    | '/admin/courses/$courseId'
    | '/admin/courses/edit'
    | '/admin/payments/payouts'
    | '/admin/payments/reported-content'
    | '/admin/payments/transactions'
    | '/admin/users/audit-logs'
    | '/learner/encyclopedia/$articleId'
    | '/learner/learn/$courseId'
    | '/learner/profile/edit'
    | '/mentor/analytics/completion'
    | '/mentor/analytics/courses'
    | '/mentor/analytics/engagement'
    | '/mentor/courses/create'
    | '/mentor/earnings/withdrawals'
    | '/mentor/encyclopedia/$articleId'
    | '/mentor/encyclopedia/create'
    | '/mentor/profile/edit'
    | '/mentor/students/$studentId'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/learner/certificates'
    | '/learner/community'
    | '/learner/encyclopedia'
    | '/learner/notifications'
    | '/learner/profile'
    | '/learner/saved'
    | '/learner/settings'
    | '/mentor/analytics'
    | '/mentor/community'
    | '/mentor/courses'
    | '/mentor/earnings'
    | '/mentor/encyclopedia'
    | '/mentor/notifications'
    | '/mentor/profile'
    | '/mentor/reviews'
    | '/mentor/settings'
    | '/mentor/students'
    | '/learner/community/discussions/$discussionId'
    | '/learner/community/discussions/new'
    | '/learner/community/events/$eventId'
    | '/learner/community/events/create'
    | '/learner/courses/courses/$courseId'
    | '/learner/mentors/mentors/$mentorId'
    | '/mentor/community/discussions/$discussionId'
    | '/mentor/community/discussions/new'
    | '/mentor/community/events/$eventId'
    | '/mentor/community/events/create'
    | '/mentor/courses/edit/$courseId'
    | '/mentor/courses/manage/$courseId'
    | '/mentor/courses/manage/certificates'
    | '/mentor/encyclopedia/$articleId/edit'
    | '/admin/users/mentors'
    | '/learner/community/discussions'
    | '/learner/community/events'
    | '/learner/courses/courses'
    | '/learner/mentors/mentors'
    | '/mentor/community/discussions'
    | '/mentor/community/events'
    | '/learner/community/events/$eventId/edit'
    | '/mentor/community/events/$eventId/edit'
    | '/mentor/courses/manage/reviews/$courseId'
  id:
    | '__root__'
    | '/'
    | '/apply-mentor'
    | '/login'
    | '/mentor-application-success'
    | '/register'
    | '/support'
    | '/admin/_layout'
    | '/admin/dashboard'
    | '/learner/_layout'
    | '/learner/checkout'
    | '/learner/dashboard'
    | '/learner/payment-success'
    | '/mentor/_layout'
    | '/mentor/dashboard'
    | '/admin/courses/$courseId'
    | '/admin/courses/edit'
    | '/admin/payments/payouts'
    | '/admin/payments/reported-content'
    | '/admin/payments/transactions'
    | '/admin/users/audit-logs'
    | '/learner/encyclopedia/$articleId'
    | '/learner/learn/$courseId'
    | '/learner/profile/edit'
    | '/mentor/analytics/completion'
    | '/mentor/analytics/courses'
    | '/mentor/analytics/engagement'
    | '/mentor/courses/create'
    | '/mentor/earnings/withdrawals'
    | '/mentor/encyclopedia/$articleId'
    | '/mentor/encyclopedia/create'
    | '/mentor/profile/edit'
    | '/mentor/students/$studentId'
    | '/admin/analytics/'
    | '/admin/courses/'
    | '/admin/events/'
    | '/admin/payments/'
    | '/admin/profile/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/learner/certificates/'
    | '/learner/community/'
    | '/learner/encyclopedia/'
    | '/learner/notifications/'
    | '/learner/profile/'
    | '/learner/saved/'
    | '/learner/settings/'
    | '/mentor/analytics/'
    | '/mentor/community/'
    | '/mentor/courses/'
    | '/mentor/earnings/'
    | '/mentor/encyclopedia/'
    | '/mentor/notifications/'
    | '/mentor/profile/'
    | '/mentor/reviews/'
    | '/mentor/settings/'
    | '/mentor/students/'
    | '/learner/community/discussions/$discussionId'
    | '/learner/community/discussions/new'
    | '/learner/community/events/$eventId'
    | '/learner/community/events/create'
    | '/learner/courses/courses/$courseId'
    | '/learner/mentors/mentors/$mentorId'
    | '/mentor/community/discussions/$discussionId'
    | '/mentor/community/discussions/new'
    | '/mentor/community/events/$eventId'
    | '/mentor/community/events/create'
    | '/mentor/courses/edit/$courseId'
    | '/mentor/courses/manage/$courseId'
    | '/mentor/courses/manage/certificates'
    | '/mentor/encyclopedia/$articleId/edit'
    | '/admin/users/mentors/'
    | '/learner/community/discussions/'
    | '/learner/community/events/'
    | '/learner/courses/courses/'
    | '/learner/mentors/mentors/'
    | '/mentor/community/discussions/'
    | '/mentor/community/events/'
    | '/learner/community/events/$eventId/edit'
    | '/mentor/community/events/$eventId/edit'
    | '/mentor/courses/manage/reviews/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyMentorRoute: typeof ApplyMentorRoute
  LoginRoute: typeof LoginRoute
  MentorApplicationSuccessRoute: typeof MentorApplicationSuccessRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  LearnerLayoutRoute: typeof LearnerLayoutRoute
  LearnerCheckoutRoute: typeof LearnerCheckoutRoute
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerPaymentSuccessRoute: typeof LearnerPaymentSuccessRoute
  MentorLayoutRoute: typeof MentorLayoutRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesEditRoute: typeof AdminCoursesEditRoute
  AdminPaymentsPayoutsRoute: typeof AdminPaymentsPayoutsRoute
  AdminPaymentsReportedContentRoute: typeof AdminPaymentsReportedContentRoute
  AdminPaymentsTransactionsRoute: typeof AdminPaymentsTransactionsRoute
  AdminUsersAuditLogsRoute: typeof AdminUsersAuditLogsRoute
  LearnerEncyclopediaArticleIdRoute: typeof LearnerEncyclopediaArticleIdRoute
  LearnerLearnCourseIdRoute: typeof LearnerLearnCourseIdRoute
  LearnerProfileEditRoute: typeof LearnerProfileEditRoute
  MentorAnalyticsCompletionRoute: typeof MentorAnalyticsCompletionRoute
  MentorAnalyticsCoursesRoute: typeof MentorAnalyticsCoursesRoute
  MentorAnalyticsEngagementRoute: typeof MentorAnalyticsEngagementRoute
  MentorCoursesCreateRoute: typeof MentorCoursesCreateRoute
  MentorEarningsWithdrawalsRoute: typeof MentorEarningsWithdrawalsRoute
  MentorEncyclopediaArticleIdRoute: typeof MentorEncyclopediaArticleIdRouteWithChildren
  MentorEncyclopediaCreateRoute: typeof MentorEncyclopediaCreateRoute
  MentorProfileEditRoute: typeof MentorProfileEditRoute
  MentorStudentsStudentIdRoute: typeof MentorStudentsStudentIdRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  LearnerCertificatesIndexRoute: typeof LearnerCertificatesIndexRoute
  LearnerCommunityIndexRoute: typeof LearnerCommunityIndexRoute
  LearnerEncyclopediaIndexRoute: typeof LearnerEncyclopediaIndexRoute
  LearnerNotificationsIndexRoute: typeof LearnerNotificationsIndexRoute
  LearnerProfileIndexRoute: typeof LearnerProfileIndexRoute
  LearnerSavedIndexRoute: typeof LearnerSavedIndexRoute
  LearnerSettingsIndexRoute: typeof LearnerSettingsIndexRoute
  MentorAnalyticsIndexRoute: typeof MentorAnalyticsIndexRoute
  MentorCommunityIndexRoute: typeof MentorCommunityIndexRoute
  MentorCoursesIndexRoute: typeof MentorCoursesIndexRoute
  MentorEarningsIndexRoute: typeof MentorEarningsIndexRoute
  MentorEncyclopediaIndexRoute: typeof MentorEncyclopediaIndexRoute
  MentorNotificationsIndexRoute: typeof MentorNotificationsIndexRoute
  MentorProfileIndexRoute: typeof MentorProfileIndexRoute
  MentorReviewsIndexRoute: typeof MentorReviewsIndexRoute
  MentorSettingsIndexRoute: typeof MentorSettingsIndexRoute
  MentorStudentsIndexRoute: typeof MentorStudentsIndexRoute
  LearnerCommunityDiscussionsDiscussionIdRoute: typeof LearnerCommunityDiscussionsDiscussionIdRoute
  LearnerCommunityDiscussionsNewRoute: typeof LearnerCommunityDiscussionsNewRoute
  LearnerCommunityEventsEventIdRoute: typeof LearnerCommunityEventsEventIdRouteWithChildren
  LearnerCommunityEventsCreateRoute: typeof LearnerCommunityEventsCreateRoute
  LearnerCoursesCoursesCourseIdRoute: typeof LearnerCoursesCoursesCourseIdRoute
  LearnerMentorsMentorsMentorIdRoute: typeof LearnerMentorsMentorsMentorIdRoute
  MentorCommunityDiscussionsDiscussionIdRoute: typeof MentorCommunityDiscussionsDiscussionIdRoute
  MentorCommunityDiscussionsNewRoute: typeof MentorCommunityDiscussionsNewRoute
  MentorCommunityEventsEventIdRoute: typeof MentorCommunityEventsEventIdRouteWithChildren
  MentorCommunityEventsCreateRoute: typeof MentorCommunityEventsCreateRoute
  MentorCoursesEditCourseIdRoute: typeof MentorCoursesEditCourseIdRoute
  MentorCoursesManageCourseIdRoute: typeof MentorCoursesManageCourseIdRoute
  MentorCoursesManageCertificatesRoute: typeof MentorCoursesManageCertificatesRoute
  AdminUsersMentorsIndexRoute: typeof AdminUsersMentorsIndexRoute
  LearnerCommunityDiscussionsIndexRoute: typeof LearnerCommunityDiscussionsIndexRoute
  LearnerCommunityEventsIndexRoute: typeof LearnerCommunityEventsIndexRoute
  LearnerCoursesCoursesIndexRoute: typeof LearnerCoursesCoursesIndexRoute
  LearnerMentorsMentorsIndexRoute: typeof LearnerMentorsMentorsIndexRoute
  MentorCommunityDiscussionsIndexRoute: typeof MentorCommunityDiscussionsIndexRoute
  MentorCommunityEventsIndexRoute: typeof MentorCommunityEventsIndexRoute
  MentorCoursesManageReviewsCourseIdRoute: typeof MentorCoursesManageReviewsCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-application-success': {
      id: '/mentor-application-success'
      path: '/mentor-application-success'
      fullPath: '/mentor-application-success'
      preLoaderRoute: typeof MentorApplicationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-mentor': {
      id: '/apply-mentor'
      path: '/apply-mentor'
      fullPath: '/apply-mentor'
      preLoaderRoute: typeof ApplyMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/_layout': {
      id: '/mentor/_layout'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/payment-success': {
      id: '/learner/payment-success'
      path: '/learner/payment-success'
      fullPath: '/learner/payment-success'
      preLoaderRoute: typeof LearnerPaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/dashboard': {
      id: '/learner/dashboard'
      path: '/learner/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/checkout': {
      id: '/learner/checkout'
      path: '/learner/checkout'
      fullPath: '/learner/checkout'
      preLoaderRoute: typeof LearnerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/_layout': {
      id: '/learner/_layout'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/students/': {
      id: '/mentor/students/'
      path: '/mentor/students'
      fullPath: '/mentor/students/'
      preLoaderRoute: typeof MentorStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/settings/': {
      id: '/mentor/settings/'
      path: '/mentor/settings'
      fullPath: '/mentor/settings/'
      preLoaderRoute: typeof MentorSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/reviews/': {
      id: '/mentor/reviews/'
      path: '/mentor/reviews'
      fullPath: '/mentor/reviews/'
      preLoaderRoute: typeof MentorReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/profile/': {
      id: '/mentor/profile/'
      path: '/mentor/profile'
      fullPath: '/mentor/profile/'
      preLoaderRoute: typeof MentorProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/notifications/': {
      id: '/mentor/notifications/'
      path: '/mentor/notifications'
      fullPath: '/mentor/notifications/'
      preLoaderRoute: typeof MentorNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/encyclopedia/': {
      id: '/mentor/encyclopedia/'
      path: '/mentor/encyclopedia'
      fullPath: '/mentor/encyclopedia/'
      preLoaderRoute: typeof MentorEncyclopediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/earnings/': {
      id: '/mentor/earnings/'
      path: '/mentor/earnings'
      fullPath: '/mentor/earnings/'
      preLoaderRoute: typeof MentorEarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses/': {
      id: '/mentor/courses/'
      path: '/mentor/courses'
      fullPath: '/mentor/courses/'
      preLoaderRoute: typeof MentorCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/': {
      id: '/mentor/community/'
      path: '/mentor/community'
      fullPath: '/mentor/community/'
      preLoaderRoute: typeof MentorCommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics/': {
      id: '/mentor/analytics/'
      path: '/mentor/analytics'
      fullPath: '/mentor/analytics/'
      preLoaderRoute: typeof MentorAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/settings/': {
      id: '/learner/settings/'
      path: '/learner/settings'
      fullPath: '/learner/settings/'
      preLoaderRoute: typeof LearnerSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/saved/': {
      id: '/learner/saved/'
      path: '/learner/saved'
      fullPath: '/learner/saved/'
      preLoaderRoute: typeof LearnerSavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/profile/': {
      id: '/learner/profile/'
      path: '/learner/profile'
      fullPath: '/learner/profile/'
      preLoaderRoute: typeof LearnerProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/notifications/': {
      id: '/learner/notifications/'
      path: '/learner/notifications'
      fullPath: '/learner/notifications/'
      preLoaderRoute: typeof LearnerNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/encyclopedia/': {
      id: '/learner/encyclopedia/'
      path: '/learner/encyclopedia'
      fullPath: '/learner/encyclopedia/'
      preLoaderRoute: typeof LearnerEncyclopediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/': {
      id: '/learner/community/'
      path: '/learner/community'
      fullPath: '/learner/community/'
      preLoaderRoute: typeof LearnerCommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/certificates/': {
      id: '/learner/certificates/'
      path: '/learner/certificates'
      fullPath: '/learner/certificates/'
      preLoaderRoute: typeof LearnerCertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/admin/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/admin/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/admin/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/students/$studentId': {
      id: '/mentor/students/$studentId'
      path: '/mentor/students/$studentId'
      fullPath: '/mentor/students/$studentId'
      preLoaderRoute: typeof MentorStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/profile/edit': {
      id: '/mentor/profile/edit'
      path: '/mentor/profile/edit'
      fullPath: '/mentor/profile/edit'
      preLoaderRoute: typeof MentorProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/encyclopedia/create': {
      id: '/mentor/encyclopedia/create'
      path: '/mentor/encyclopedia/create'
      fullPath: '/mentor/encyclopedia/create'
      preLoaderRoute: typeof MentorEncyclopediaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/encyclopedia/$articleId': {
      id: '/mentor/encyclopedia/$articleId'
      path: '/mentor/encyclopedia/$articleId'
      fullPath: '/mentor/encyclopedia/$articleId'
      preLoaderRoute: typeof MentorEncyclopediaArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/earnings/withdrawals': {
      id: '/mentor/earnings/withdrawals'
      path: '/mentor/earnings/withdrawals'
      fullPath: '/mentor/earnings/withdrawals'
      preLoaderRoute: typeof MentorEarningsWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses/create': {
      id: '/mentor/courses/create'
      path: '/mentor/courses/create'
      fullPath: '/mentor/courses/create'
      preLoaderRoute: typeof MentorCoursesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics/engagement': {
      id: '/mentor/analytics/engagement'
      path: '/mentor/analytics/engagement'
      fullPath: '/mentor/analytics/engagement'
      preLoaderRoute: typeof MentorAnalyticsEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics/courses': {
      id: '/mentor/analytics/courses'
      path: '/mentor/analytics/courses'
      fullPath: '/mentor/analytics/courses'
      preLoaderRoute: typeof MentorAnalyticsCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/analytics/completion': {
      id: '/mentor/analytics/completion'
      path: '/mentor/analytics/completion'
      fullPath: '/mentor/analytics/completion'
      preLoaderRoute: typeof MentorAnalyticsCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/profile/edit': {
      id: '/learner/profile/edit'
      path: '/learner/profile/edit'
      fullPath: '/learner/profile/edit'
      preLoaderRoute: typeof LearnerProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/learn/$courseId': {
      id: '/learner/learn/$courseId'
      path: '/learner/learn/$courseId'
      fullPath: '/learner/learn/$courseId'
      preLoaderRoute: typeof LearnerLearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/encyclopedia/$articleId': {
      id: '/learner/encyclopedia/$articleId'
      path: '/learner/encyclopedia/$articleId'
      fullPath: '/learner/encyclopedia/$articleId'
      preLoaderRoute: typeof LearnerEncyclopediaArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/audit-logs': {
      id: '/admin/users/audit-logs'
      path: '/admin/users/audit-logs'
      fullPath: '/admin/users/audit-logs'
      preLoaderRoute: typeof AdminUsersAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/transactions': {
      id: '/admin/payments/transactions'
      path: '/admin/payments/transactions'
      fullPath: '/admin/payments/transactions'
      preLoaderRoute: typeof AdminPaymentsTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/reported-content': {
      id: '/admin/payments/reported-content'
      path: '/admin/payments/reported-content'
      fullPath: '/admin/payments/reported-content'
      preLoaderRoute: typeof AdminPaymentsReportedContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/payouts': {
      id: '/admin/payments/payouts'
      path: '/admin/payments/payouts'
      fullPath: '/admin/payments/payouts'
      preLoaderRoute: typeof AdminPaymentsPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/edit': {
      id: '/admin/courses/edit'
      path: '/admin/courses/edit'
      fullPath: '/admin/courses/edit'
      preLoaderRoute: typeof AdminCoursesEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/admin/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/events/': {
      id: '/mentor/community/events/'
      path: '/mentor/community/events'
      fullPath: '/mentor/community/events/'
      preLoaderRoute: typeof MentorCommunityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/discussions/': {
      id: '/mentor/community/discussions/'
      path: '/mentor/community/discussions'
      fullPath: '/mentor/community/discussions/'
      preLoaderRoute: typeof MentorCommunityDiscussionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/mentors/mentors/': {
      id: '/learner/mentors/mentors/'
      path: '/learner/mentors/mentors'
      fullPath: '/learner/mentors/mentors/'
      preLoaderRoute: typeof LearnerMentorsMentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/courses/courses/': {
      id: '/learner/courses/courses/'
      path: '/learner/courses/courses'
      fullPath: '/learner/courses/courses/'
      preLoaderRoute: typeof LearnerCoursesCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/events/': {
      id: '/learner/community/events/'
      path: '/learner/community/events'
      fullPath: '/learner/community/events/'
      preLoaderRoute: typeof LearnerCommunityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/discussions/': {
      id: '/learner/community/discussions/'
      path: '/learner/community/discussions'
      fullPath: '/learner/community/discussions/'
      preLoaderRoute: typeof LearnerCommunityDiscussionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/mentors/': {
      id: '/admin/users/mentors/'
      path: '/admin/users/mentors'
      fullPath: '/admin/users/mentors/'
      preLoaderRoute: typeof AdminUsersMentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/encyclopedia/$articleId/edit': {
      id: '/mentor/encyclopedia/$articleId/edit'
      path: '/edit'
      fullPath: '/mentor/encyclopedia/$articleId/edit'
      preLoaderRoute: typeof MentorEncyclopediaArticleIdEditRouteImport
      parentRoute: typeof MentorEncyclopediaArticleIdRoute
    }
    '/mentor/courses/manage/certificates': {
      id: '/mentor/courses/manage/certificates'
      path: '/mentor/courses/manage/certificates'
      fullPath: '/mentor/courses/manage/certificates'
      preLoaderRoute: typeof MentorCoursesManageCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses/manage/$courseId': {
      id: '/mentor/courses/manage/$courseId'
      path: '/mentor/courses/manage/$courseId'
      fullPath: '/mentor/courses/manage/$courseId'
      preLoaderRoute: typeof MentorCoursesManageCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses/edit/$courseId': {
      id: '/mentor/courses/edit/$courseId'
      path: '/mentor/courses/edit/$courseId'
      fullPath: '/mentor/courses/edit/$courseId'
      preLoaderRoute: typeof MentorCoursesEditCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/events/create': {
      id: '/mentor/community/events/create'
      path: '/mentor/community/events/create'
      fullPath: '/mentor/community/events/create'
      preLoaderRoute: typeof MentorCommunityEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/events/$eventId': {
      id: '/mentor/community/events/$eventId'
      path: '/mentor/community/events/$eventId'
      fullPath: '/mentor/community/events/$eventId'
      preLoaderRoute: typeof MentorCommunityEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/discussions/new': {
      id: '/mentor/community/discussions/new'
      path: '/mentor/community/discussions/new'
      fullPath: '/mentor/community/discussions/new'
      preLoaderRoute: typeof MentorCommunityDiscussionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/discussions/$discussionId': {
      id: '/mentor/community/discussions/$discussionId'
      path: '/mentor/community/discussions/$discussionId'
      fullPath: '/mentor/community/discussions/$discussionId'
      preLoaderRoute: typeof MentorCommunityDiscussionsDiscussionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/mentors/mentors/$mentorId': {
      id: '/learner/mentors/mentors/$mentorId'
      path: '/learner/mentors/mentors/$mentorId'
      fullPath: '/learner/mentors/mentors/$mentorId'
      preLoaderRoute: typeof LearnerMentorsMentorsMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/courses/courses/$courseId': {
      id: '/learner/courses/courses/$courseId'
      path: '/learner/courses/courses/$courseId'
      fullPath: '/learner/courses/courses/$courseId'
      preLoaderRoute: typeof LearnerCoursesCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/events/create': {
      id: '/learner/community/events/create'
      path: '/learner/community/events/create'
      fullPath: '/learner/community/events/create'
      preLoaderRoute: typeof LearnerCommunityEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/events/$eventId': {
      id: '/learner/community/events/$eventId'
      path: '/learner/community/events/$eventId'
      fullPath: '/learner/community/events/$eventId'
      preLoaderRoute: typeof LearnerCommunityEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/discussions/new': {
      id: '/learner/community/discussions/new'
      path: '/learner/community/discussions/new'
      fullPath: '/learner/community/discussions/new'
      preLoaderRoute: typeof LearnerCommunityDiscussionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/community/discussions/$discussionId': {
      id: '/learner/community/discussions/$discussionId'
      path: '/learner/community/discussions/$discussionId'
      fullPath: '/learner/community/discussions/$discussionId'
      preLoaderRoute: typeof LearnerCommunityDiscussionsDiscussionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/courses/manage/reviews/$courseId': {
      id: '/mentor/courses/manage/reviews/$courseId'
      path: '/mentor/courses/manage/reviews/$courseId'
      fullPath: '/mentor/courses/manage/reviews/$courseId'
      preLoaderRoute: typeof MentorCoursesManageReviewsCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/community/events/$eventId/edit': {
      id: '/mentor/community/events/$eventId/edit'
      path: '/edit'
      fullPath: '/mentor/community/events/$eventId/edit'
      preLoaderRoute: typeof MentorCommunityEventsEventIdEditRouteImport
      parentRoute: typeof MentorCommunityEventsEventIdRoute
    }
    '/learner/community/events/$eventId/edit': {
      id: '/learner/community/events/$eventId/edit'
      path: '/edit'
      fullPath: '/learner/community/events/$eventId/edit'
      preLoaderRoute: typeof LearnerCommunityEventsEventIdEditRouteImport
      parentRoute: typeof LearnerCommunityEventsEventIdRoute
    }
  }
}

interface MentorEncyclopediaArticleIdRouteChildren {
  MentorEncyclopediaArticleIdEditRoute: typeof MentorEncyclopediaArticleIdEditRoute
}

const MentorEncyclopediaArticleIdRouteChildren: MentorEncyclopediaArticleIdRouteChildren =
  {
    MentorEncyclopediaArticleIdEditRoute: MentorEncyclopediaArticleIdEditRoute,
  }

const MentorEncyclopediaArticleIdRouteWithChildren =
  MentorEncyclopediaArticleIdRoute._addFileChildren(
    MentorEncyclopediaArticleIdRouteChildren,
  )

interface LearnerCommunityEventsEventIdRouteChildren {
  LearnerCommunityEventsEventIdEditRoute: typeof LearnerCommunityEventsEventIdEditRoute
}

const LearnerCommunityEventsEventIdRouteChildren: LearnerCommunityEventsEventIdRouteChildren =
  {
    LearnerCommunityEventsEventIdEditRoute:
      LearnerCommunityEventsEventIdEditRoute,
  }

const LearnerCommunityEventsEventIdRouteWithChildren =
  LearnerCommunityEventsEventIdRoute._addFileChildren(
    LearnerCommunityEventsEventIdRouteChildren,
  )

interface MentorCommunityEventsEventIdRouteChildren {
  MentorCommunityEventsEventIdEditRoute: typeof MentorCommunityEventsEventIdEditRoute
}

const MentorCommunityEventsEventIdRouteChildren: MentorCommunityEventsEventIdRouteChildren =
  {
    MentorCommunityEventsEventIdEditRoute:
      MentorCommunityEventsEventIdEditRoute,
  }

const MentorCommunityEventsEventIdRouteWithChildren =
  MentorCommunityEventsEventIdRoute._addFileChildren(
    MentorCommunityEventsEventIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyMentorRoute: ApplyMentorRoute,
  LoginRoute: LoginRoute,
  MentorApplicationSuccessRoute: MentorApplicationSuccessRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  LearnerLayoutRoute: LearnerLayoutRoute,
  LearnerCheckoutRoute: LearnerCheckoutRoute,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerPaymentSuccessRoute: LearnerPaymentSuccessRoute,
  MentorLayoutRoute: MentorLayoutRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesEditRoute: AdminCoursesEditRoute,
  AdminPaymentsPayoutsRoute: AdminPaymentsPayoutsRoute,
  AdminPaymentsReportedContentRoute: AdminPaymentsReportedContentRoute,
  AdminPaymentsTransactionsRoute: AdminPaymentsTransactionsRoute,
  AdminUsersAuditLogsRoute: AdminUsersAuditLogsRoute,
  LearnerEncyclopediaArticleIdRoute: LearnerEncyclopediaArticleIdRoute,
  LearnerLearnCourseIdRoute: LearnerLearnCourseIdRoute,
  LearnerProfileEditRoute: LearnerProfileEditRoute,
  MentorAnalyticsCompletionRoute: MentorAnalyticsCompletionRoute,
  MentorAnalyticsCoursesRoute: MentorAnalyticsCoursesRoute,
  MentorAnalyticsEngagementRoute: MentorAnalyticsEngagementRoute,
  MentorCoursesCreateRoute: MentorCoursesCreateRoute,
  MentorEarningsWithdrawalsRoute: MentorEarningsWithdrawalsRoute,
  MentorEncyclopediaArticleIdRoute:
    MentorEncyclopediaArticleIdRouteWithChildren,
  MentorEncyclopediaCreateRoute: MentorEncyclopediaCreateRoute,
  MentorProfileEditRoute: MentorProfileEditRoute,
  MentorStudentsStudentIdRoute: MentorStudentsStudentIdRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  LearnerCertificatesIndexRoute: LearnerCertificatesIndexRoute,
  LearnerCommunityIndexRoute: LearnerCommunityIndexRoute,
  LearnerEncyclopediaIndexRoute: LearnerEncyclopediaIndexRoute,
  LearnerNotificationsIndexRoute: LearnerNotificationsIndexRoute,
  LearnerProfileIndexRoute: LearnerProfileIndexRoute,
  LearnerSavedIndexRoute: LearnerSavedIndexRoute,
  LearnerSettingsIndexRoute: LearnerSettingsIndexRoute,
  MentorAnalyticsIndexRoute: MentorAnalyticsIndexRoute,
  MentorCommunityIndexRoute: MentorCommunityIndexRoute,
  MentorCoursesIndexRoute: MentorCoursesIndexRoute,
  MentorEarningsIndexRoute: MentorEarningsIndexRoute,
  MentorEncyclopediaIndexRoute: MentorEncyclopediaIndexRoute,
  MentorNotificationsIndexRoute: MentorNotificationsIndexRoute,
  MentorProfileIndexRoute: MentorProfileIndexRoute,
  MentorReviewsIndexRoute: MentorReviewsIndexRoute,
  MentorSettingsIndexRoute: MentorSettingsIndexRoute,
  MentorStudentsIndexRoute: MentorStudentsIndexRoute,
  LearnerCommunityDiscussionsDiscussionIdRoute:
    LearnerCommunityDiscussionsDiscussionIdRoute,
  LearnerCommunityDiscussionsNewRoute: LearnerCommunityDiscussionsNewRoute,
  LearnerCommunityEventsEventIdRoute:
    LearnerCommunityEventsEventIdRouteWithChildren,
  LearnerCommunityEventsCreateRoute: LearnerCommunityEventsCreateRoute,
  LearnerCoursesCoursesCourseIdRoute: LearnerCoursesCoursesCourseIdRoute,
  LearnerMentorsMentorsMentorIdRoute: LearnerMentorsMentorsMentorIdRoute,
  MentorCommunityDiscussionsDiscussionIdRoute:
    MentorCommunityDiscussionsDiscussionIdRoute,
  MentorCommunityDiscussionsNewRoute: MentorCommunityDiscussionsNewRoute,
  MentorCommunityEventsEventIdRoute:
    MentorCommunityEventsEventIdRouteWithChildren,
  MentorCommunityEventsCreateRoute: MentorCommunityEventsCreateRoute,
  MentorCoursesEditCourseIdRoute: MentorCoursesEditCourseIdRoute,
  MentorCoursesManageCourseIdRoute: MentorCoursesManageCourseIdRoute,
  MentorCoursesManageCertificatesRoute: MentorCoursesManageCertificatesRoute,
  AdminUsersMentorsIndexRoute: AdminUsersMentorsIndexRoute,
  LearnerCommunityDiscussionsIndexRoute: LearnerCommunityDiscussionsIndexRoute,
  LearnerCommunityEventsIndexRoute: LearnerCommunityEventsIndexRoute,
  LearnerCoursesCoursesIndexRoute: LearnerCoursesCoursesIndexRoute,
  LearnerMentorsMentorsIndexRoute: LearnerMentorsMentorsIndexRoute,
  MentorCommunityDiscussionsIndexRoute: MentorCommunityDiscussionsIndexRoute,
  MentorCommunityEventsIndexRoute: MentorCommunityEventsIndexRoute,
  MentorCoursesManageReviewsCourseIdRoute:
    MentorCoursesManageReviewsCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
